#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
xsetroot -cursor_name left_ptr &
xset r rate 350 20 &
# syncthing &
wal -R &
$HOME/.config/polybar/launch.sh &
dunst -conf $HOME/.config/dunst/dunstrc &
#flameshot &
picom &
xrdb merge ~/.Xresources &
ibus-daemon -drxR &
~/bin/battery-alert &
amixer set Master 0
amixer set Master mute

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         0
bspc config window_gap           8
bscp config top_padding		 0

bspc config split_ratio          0.55
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Zathura	state=tiled

# pywal 
. "${HOME}/.cache/wal/colors.sh"
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
bspc config presel_feedback_color "$color1"
